services:
    memgraph:
        image: "memgraph/memgraph-platform"
        ports:
            - "7687:7687"
        volumes:
            - mg_lib:/var/lib/memgraph
            - mg_log:/var/log/memgraph
            - mg_etc:/etc/memgraph
        environment:
            - MEMGRAPH_LOG_LEVEL=TRACE
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "true"]
            interval: 10s
            timeout: 5s
            retries: 3

    service:
        container_name: $CONTAINER_NAME
        image: krinkin/$PROJECT.$SERVICE_NAME:$BRANCH
        ports:
            - "5000"
        env_file:
            - ./.env
        volumes:
            - $CONTAINER_DATA:/data
            - $VERSION_FILE:/VERSION:ro
        depends_on:
            - memgraph
        networks:
            - app-network
        restart: unless-stopped

    tunnel:
        container_name: ${CONTAINER_NAME}_tunnel
        depends_on:
            - service
        env_file:
            - ./.env
        image: cloudflare/cloudflared:latest
        command: [ "tunnel",
                   "--no-autoupdate",
                   "run",
                   "--token",
                   "$CF_TOKEN"
        ]
        networks:
            - app-network

networks:
    app-network:

volumes:
    mg_lib:
    mg_log:
    mg_etc:
